In [1]:
from pennylane import numpy as np

In [2]:
state = np.array([1j/np.sqrt(2), 1/np.sqrt(2)])

In [83]:
state

tensor([0.        +0.70710678j, 0.70710678+0.j        ], requires_grad=True)

In [84]:
state**2

tensor([-0.5+0.j,  0.5+0.j], requires_grad=True)

In [85]:
np.real(np.conj(state)*state)

tensor([0.5, 0.5], requires_grad=True)

In [86]:
np.conj(state)

tensor([0.        -0.70710678j, 0.70710678-0.j        ], requires_grad=True)

In [87]:
num_meas = 100

In [88]:
np.random.choice([0,1], size = num_meas, p = np.real(np.conj(state)*state))


tensor([1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1], requires_grad=True)

In [89]:
for i in range(10):
    print(np.mean(np.random.choice([0,1], size = num_meas, p = np.real(np.conj(state)*state))))

0.51
0.49
0.57
0.47
0.58
0.5
0.54
0.57
0.48
0.44


In [71]:
state = np.array([.5j, .5])

In [72]:
np.sqrt(np.inner(np.conj(state),state).real)

0.7071067811865476

In [73]:
norm = np.sqrt(np.inner(np.conj(state),state).real)

In [74]:
state = state/norm

In [75]:
state

tensor([0.        +0.70710678j, 0.70710678+0.j        ], requires_grad=True)

In [76]:
np.sqrt(np.inner(np.conj(state),state).real)

0.9999999999999999

In [77]:
np.conj(state[0])*state[0]

tensor(0.5+0.j, requires_grad=True)

In [78]:
np.conj(state[1])*state[1]

tensor(0.5+0.j, requires_grad=True)

In [79]:
np.real(np.conj(state)*state)

tensor([0.5, 0.5], requires_grad=True)

In [80]:
state

tensor([0.        +0.70710678j, 0.70710678+0.j        ], requires_grad=True)

In [81]:
np.random.choice([0,1], size = num_meas, p = np.real(np.conj(state)*state))


tensor([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], requires_grad=True)

In [82]:
for i in range(10):
    print(np.mean(np.random.choice([0,1], size = num_meas, p = np.real(np.conj(state)*state))))

0.5
0.53
0.44
0.58
0.47
0.53
0.45
0.5
0.59
0.43


In [105]:
num_meas = 500

In [106]:
measures = np.random.choice(list(range(len(state))), size = num_meas, p = np.real(np.conj(state)*state))

In [107]:
np.mean(measures)

tensor(0.528, requires_grad=True)

In [108]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

In [109]:
np.matmul(U, state)

tensor([ 0.5+0.5j, -0.5+0.5j], requires_grad=True)

In [110]:
state

tensor([0.        +0.70710678j, 0.70710678+0.j        ], requires_grad=True)

In [111]:
state = np.array([1,0])

In [112]:
state

tensor([1, 0], requires_grad=True)

In [113]:
np.matmul(U, state)

tensor([0.70710678, 0.70710678], requires_grad=True)

In [114]:
state = np.array([0,1])

In [115]:
np.matmul(U, state)

tensor([ 0.70710678, -0.70710678], requires_grad=True)